- name: app set-up
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: mongodb setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup

- name: systemd start
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

- name: deployment
  ansible.builtin.import_role:
    name: common
    tasks_from: deployment
